[package]
name = "mvec-av"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
ofps = { version = "0.1", path = "../ofps" }
nalgebra = "0.30"
ffmpeg-sys = "4.3"
libc = "*"
c_str_macro = "1"
log = "0.4"
