
[profile.release]
debug = true

[workspace]
resolver = "2"

members = [
	"motion-vectors",
	"motion-visualiser",
	"mvec-av",
	"ptrplus"
]

default-members = [
	"motion-vectors",
	"motion-visualiser",
	"mvec-av",
]

