
[profile.release]
debug = true

[workspace]
resolver = "2"

members = [
	"motion-vectors",
	"motion-visualiser",
	"motion-loader",
	"motion-extract",
	"motion-analyser",
	"mvec-av",
	"mvec-cv",
	"ptrplus",
	"libmv-rust",
]

default-members = [
	"motion-vectors",
	"motion-visualiser",
	"motion-loader",
	"motion-extract",
	"motion-analyser",
	"mvec-av",
	"libmv-rust",
	#"mvec-cv",
]

