[package]
name = "homography-estimator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
ofps = { version = "0.1", path = "../ofps" }
nalgebra = "0.30"
rand = "0.8"
opencv = { version = "0.62", features = ["clang-runtime"] }
noisy_float = "0.2"
